### ISSUE TITLE
Digiline button can easily overheat luacontrollers

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/digistuff#2]
Root cause is that digiline messages rate is basically limited by player click rate, this is primarily problem with public buttons. Most probably owner of protected button does not wnat to do this although it is possible to do this by accident if luacontroller is already pushed near limits.

This can be easily fixed by removing click handlers completely from _on state buttons:

https://github.com/pandorabox-io/digistuff/blob/4e1a37e167c50e5b25b344cf2df999a868821c3e/button.lua#L158-L167

**Comment by thomasrudin** [comment]
maybe this was caused by a setting in `minetest.conf`:
```
mesecon.overheat_max = 6
```

i removed that again, because i added that a few months back when we still had perf issues..
Default value should be 10 i think.

The setting is applied, as is the digistuff update, but the server needs a restart/crash...

**Comment by S-S-X** [comment]
Seems that this is not problem after configuration has been updated, at least not with empty controller.

**Comment by thomasrudin** [comment]
Can this be closed? Is that still an issue?
